name: build

on:
  push:
    branches:
    - master
    paths:
    - image/**
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Building image"
