name: Publish image

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  publish:
    name: Push
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Inspect upstream
      id: upstream
      uses: ./.github/actions/upstream

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        context: image
        build-args: |-
          recorder=${{ steps.upstream.outputs.recorder-rev }}
          converter=${{ steps.upstream.outputs.converter-rev }}
        tags: |-
          ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ steps.upstream.outputs.recorder-short-rev }}-${{ steps.upstream.outputs.converter-short-rev }}
          ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:latest
