name: Publish upstream changes

on:
  pull_request:
    branches:
    - master

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.image.outputs.changes }}

    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: .github/actions/upstream/action.yml
        sparse-checkout-cone-mode: false

    - name: Inspect upstream
      id: upstream
      uses: ./.github/actions/upstream

    - name: Check if image exists
      id: image
      run: |-
        if docker manifest inspect ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ steps.upstream.outputs.recorder-short-rev }}-${{ steps.upstream.outputs.converter-short-rev }}; then
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "changes=true" >> $GITHUB_OUTPUT
        fi

  publish:
    needs: check
    if: needs.check.outputs.changes == 'true'
    uses: ./.github/workflows/publish.yml
